name: trackrx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  assets: ^0.0.1
  google_fonts: ^6.2.1  
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  image_picker: ^1.1.2
  flutter_check_box_rounded: ^3.2.3
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  pretty_qr_code: ^3.3.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.3
  firebase_auth: ^5.3.3
  flutter_slidable: ^3.1.1
  firebase_storage: ^12.3.6
  fl_chart: ^0.69.1
  animated_snack_bar: ^0.4.0
  splash_screen_view: ^2.0.1
  lottie: ^3.1.3
  sqflite: ^2.4.1
  audioplayers: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/patient/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/patient/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/patient/
    - assets/
    - assets/manufacturer/
    - assets/emergency.mp3
    


